CREATE OR REPLACE TABLE `rh-etl-project-467521.MMM_datset.mmm` AS
SELECT
  DATE(PARSE_DATE('%d-%m-%Y', DATE_DAY)) AS date_day,

  ORGANISATION_VERTICAL AS organisation_vertical,
  ORGANISATION_SUBVERTICAL AS organisation_subvertical,
  ORGANISATION_PRIMARY_TERRITORY_NAME AS territory,

  FIRST_PURCHASES_ORIGINAL_PRICE AS revenue,

  GOOGLE_PAID_SEARCH_SPEND,
  GOOGLE_SHOPPING_SPEND,
  GOOGLE_PMAX_SPEND,
  GOOGLE_DISPLAY_SPEND,
  GOOGLE_VIDEO_SPEND,

  META_FACEBOOK_SPEND,
  META_INSTAGRAM_SPEND,
  META_OTHER_SPEND,
  TIKTOK_SPEND,

  GOOGLE_PAID_SEARCH_CLICKS + GOOGLE_SHOPPING_CLICKS +
  GOOGLE_PMAX_CLICKS + GOOGLE_DISPLAY_CLICKS +
  META_FACEBOOK_CLICKS + TIKTOK_CLICKS AS clicks,

  GOOGLE_PAID_SEARCH_IMPRESSIONS +
  GOOGLE_DISPLAY_IMPRESSIONS +
  META_FACEBOOK_IMPRESSIONS +
  TIKTOK_IMPRESSIONS AS impressions

FROM `project_id.dataset_name.compressed_data`;